import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Cursor from '@/components/Cursor'
const poppins = Poppins({
  weight: ['400', '500' , '600' ,'700' , '800' , '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'My portfolio',
  description: 'Generated by create my portfolio',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Cursor/>
        <Header/>
        {children}
      </body>
    </html>
  )
}
